---
language: node_js
node_js:
  - "0.10"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - "npm --version"

install:
  - "npm install"

script:
  - npm test


